FROM khipu/openjdk21-alpine

COPY target/Ideapedia.jar /docker-build/Ideapedia.jar
CMD ["java","-jar","/docker-build/Ideapedia.jar"]

#COPY src /home/app/src
#COPY pom.xml /home/app
#RUN mvn -f /home/app/pom.xml clean install -DskipTest=true